stages:
  - build

before_script:
  - docker info

build_smalink:
  stage: build
  script:
    - docker-compose up -d --build
    - docker ps
    - docker exec $(docker ps -f name=smalink_fpm -q) composer install
