main_site_homepage:
    pattern:  /
    defaults: { _controller: MainSiteBundle:Default:index }

main_site_stats:
    pattern:  /stats
    defaults: { _controller: MainSiteBundle:Default:stats }



google_charts_pie:
    pattern:  /pieChart/{id}
    defaults: { _controller: MainSiteBundle:Default:pie }

google_charts_pie3D:
    pattern:  /pie3DChart/{id}
    defaults: { _controller: MainSiteBundle:Default:pie3D }

google_charts_bar:
    pattern:  /barChart/{id}
    defaults: { _controller: MainSiteBundle:Default:bar }



main_site_dashboard:
    pattern:  /dashboard
    defaults: { _controller: MainSiteBundle:Default:dashboard }

main_site_links:
    pattern:  /links
    defaults: { _controller: MainSiteBundle:Default:allLinks }

main_site_getlink:
    pattern:  /links/{id}
    defaults: { _controller: MainSiteBundle:Default:linkInfo, id: 0 }
    requirements:
        id: \d+

main_site_newlink:
    pattern:  /links/create
    defaults: { _controller: MainSiteBundle:Default:newLink }

main_site_supprlink:
    pattern:  /links/delete/{id}
    defaults: { _controller: MainSiteBundle:Default:supprLink }
    requirements:
        id: \d+

main_site_activelink:
    pattern:  /links/activate/{id}
    defaults: { _controller: MainSiteBundle:Default:activeLink }
    requirements:
        id: \d+




main_site_shortener:
    pattern:  /{short}
    defaults: { _controller: MainSiteBundle:Default:shortener }
