main_site_homepage:
    path:  /
    defaults: { _controller: MainSiteBundle:Default:index }

main_site_stats:
    path:  /stats
    defaults: { _controller: MainSiteBundle:Default:stats }



google_charts_pie:
    path:  /pieChart/{id}
    defaults: { _controller: MainSiteBundle:Default:pie }

google_charts_pie3D:
    path:  /pie3DChart/{id}
    defaults: { _controller: MainSiteBundle:Default:pie3D }

google_charts_bar:
    path:  /barChart/{id}
    defaults: { _controller: MainSiteBundle:Default:bar }



main_site_dashboard:
    path:  /dashboard
    defaults: { _controller: MainSiteBundle:Default:dashboard }

main_site_links:
    path:  /links
    defaults: { _controller: MainSiteBundle:Default:allLinks }

main_site_getlink:
    path:  /links/{id}
    defaults: { _controller: MainSiteBundle:Default:linkInfo, id: 0 }
    requirements: { 'id': '\d+' }

main_site_newlink:
    path:  /links/create
    defaults: { _controller: MainSiteBundle:Default:newLink }

main_site_supprlink:
    path:  /links/delete/{id}
    defaults: { _controller: MainSiteBundle:Default:supprLink }
    requirements: { 'id': '\d+' }

main_site_activelink:
    path:  /links/activate/{id}
    defaults: { _controller: MainSiteBundle:Default:activeLink }
    requirements: { 'id': '\d+' }




main_site_shortener:
    path:  /{short}
    defaults: { _controller: MainSiteBundle:Default:shortener }
